description = "thin-edge.io default recipes"
dependencies = [
    "core/apt-cleanup",
    "core/persist-root-home",
    "rugpi-extra/zsh",

    # thin-edge.io recipes
    # "persist-data",
    # "persist-network-manager",
    # "persist-overlay",
    # "tedge-bootstrap",
    # "tedge-firmware-update",
    "x-avahi-daemon",
    "set-wifi",
    "mosquitto",
    "sbom",
    "ssh",
]