description = "install thin-edge.io"
priority = 20_000

[parameters]
# Control which thin-edge.io release channel to install from
# Values:
#   release  - Latest official build
#   main     - Latest build from the main branch (bleeding edge)
channel = { default = "release" }
